### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by fommil** [hiredman/javap-mode#5]
I don't believe it is possible to license anything that uses emacs-lisp as anything other than GPL, but you have chosen a permissive license

**Comment by omajid** [comment]
Here's what [RMS has to say about emacs-lisp and GPL](https://lists.debian.org/debian-legal/2002/11/msg00217.html):

> As for the more general question, we think that a program that uses
> Emacs facilities needs to be GPL-covered, but a program that just uses
> the Lisp language could have any license--it is not affected by the
> license of Emacs.

**Comment by fommil** [comment]
Yup, that's about what I would have thought. So any use of the Emacs lisp standard library means it is gpl.
